export const TYPES = {
  GET_DATA: 'SET_DATA',
  SET_DATA: 'SET_DATA',
  SHOW_ERROR: 'SHOW_ERROR',
  CALL_SUCCESS: 'CALL_SUCCESS',
  LOADING: 'LOADING',
  START_LOADING: 'START_LOADING',
  FINISH_LOADING: 'FINISH_LOADING',
  GET_DATA_FILTER: 'GET_DATA_FILTER',
  SET_DATA_FILTER: 'SET_DATA_FILTER',
  CATEGORY: 'CATEGORY',
};
